name: Auto Join Team Battle

on:
  schedule:
    - cron: '*/15 * * * *'   # alle 15 Minuten
  workflow_dispatch:          # manuell startbar

jobs:
  join:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        env:
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }}
          LICHESS_TEAM_ID: "schachfreunde-stuttgart"
          LICHESS_CREATOR: "username_des_erstellers"
        run: python3 auto_join_team_battle.py
